#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Dec 01 19:22:18 CET 2022
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab -wto f220b767f6fc43739beeaf8db9739c3b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot counter_behav xil_defaultlib.counter -log elaborate.log"
xelab -wto f220b767f6fc43739beeaf8db9739c3b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot counter_behav xil_defaultlib.counter -log elaborate.log

