webtalk_init -webtalk_dir /home/sdu/Documents/embeddedSystems/Assignments/assignment2/Assignment2/MPSoC4Drones-main/vivado/assignment2Counter/assignment2Counter.sim/sim_1/behav/xsim/xsim.dir/counter_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Dec  1 19:25:44 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "758cb62d-d95b-4e38-b0cc-57096089d012" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f220b767f6fc43739beeaf8db9739c3b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 20.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-6300HQ CPU @ 2.30GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2300.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "21 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "116288_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2448257277 -regid "" -xml /home/sdu/Documents/embeddedSystems/Assignments/assignment2/Assignment2/MPSoC4Drones-main/vivado/assignment2Counter/assignment2Counter.sim/sim_1/behav/xsim/xsim.dir/counter_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/sdu/Documents/embeddedSystems/Assignments/assignment2/Assignment2/MPSoC4Drones-main/vivado/assignment2Counter/assignment2Counter.sim/sim_1/behav/xsim/xsim.dir/counter_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/sdu/Documents/embeddedSystems/Assignments/assignment2/Assignment2/MPSoC4Drones-main/vivado/assignment2Counter/assignment2Counter.sim/sim_1/behav/xsim/xsim.dir/counter_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
